mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=wordpress
web:
    image: wordpress:4.9.7-php7.0-apache
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=123456
    ports:
     - "0.0.0.0:80:80"
    working_dir: /var/www/html
    volumes:
     - wordpress:/var/www/html